# Generated by Django 5.0.3 on 2024-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_created_at_task_due_date_task_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
