# Generated by Django 5.0.3 on 2024-06-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mentions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
